### ISSUE TITLE
expired SSL certificate

### ISSUE THREAD

**Issue by landsman** [statoscope/statoscope.tech#11]
Website: https://statoscope.tech/

I would suggest moving the domain behind https://www.cloudflare.com and not caring about SSL certs anymore. You will also gain faster speed out of the box.

![Screenshot 2024-01-03 at 9 52 26](https://github.com/statoscope/statoscope.tech/assets/3184228/6d0a3346-11cd-4b7f-8fc1-717dbb409a46)

**Comment by smelukov** [comment]
Thanks! I've just updated the certificate
